// Generated by `bun run gen:lines`. Do not edit by hand.

#pragma once

#include <cstddef>
#include <cstdint>

struct DeviceLine {
  const char* key;
  const char* file;
};

constexpr DeviceLine kDeviceLines[] = {
    {"light_off", "/light_off.wav"},
    {"light_on", "/light_on.wav"},
    {"boot", "/boot.wav"},
};

constexpr size_t kDeviceLineCount = sizeof(kDeviceLines) / sizeof(kDeviceLines[0]);
