// Generated by `bun run gen:lines`. Do not edit by hand.

#pragma once

#include <cstddef>
#include <cstdint>

struct DeviceLine {
  const char* key;
  const char* file;
  uint16_t spinMs;
  uint16_t cooldownMs;
};

constexpr DeviceLine kDeviceLines[] = {
    {"power_on", "/power_on.wav", 400, 800},
    {"shake_1", "/shake_1.wav", 400, 800},
    {"shake_2", "/shake_2.wav", 400, 800},
    {"shake_3", "/shake_3.wav", 400, 800},
    {"power_off", "/power_off.wav", 400, 800},
};

constexpr size_t kDeviceLineCount = sizeof(kDeviceLines) / sizeof(kDeviceLines[0]);
