// Emits firmware/include/lines.gen.h from the shared line manifest.

import { promises as fsp } from 'node:fs'
import path from 'node:path'
import { loadLines, type LineEntry } from '@taffybot/voice'

const MANIFEST = path.resolve('hardware/lines.json')
const TARGET = path.resolve('firmware/include/lines.gen.h')

function renderRow(line: LineEntry): string {
  return `    {"${line.key}", "/${line.key}.wav"},`
}

function renderHeader(lines: LineEntry[]): string {
  return `// Generated by \`bun run gen:lines\`. Do not edit by hand.

#pragma once

#include <cstddef>
#include <cstdint>

struct DeviceLine {
  const char* key;
  const char* file;
};

constexpr DeviceLine kDeviceLines[] = {
${lines.map(renderRow).join('\n')}
};

constexpr size_t kDeviceLineCount = sizeof(kDeviceLines) / sizeof(kDeviceLines[0]);
`
}

async function main(): Promise<void> {
  const lines = await loadLines(MANIFEST)
  await fsp.mkdir(path.dirname(TARGET), { recursive: true })
  await fsp.writeFile(TARGET, renderHeader(lines))
  console.log(`[gen] ${lines.length} line(s) -> ${TARGET}`)
}

main().catch((error: unknown) => {
  console.error(`[gen] ${error instanceof Error ? error.message : String(error)}`)
  process.exit(1)
})
